### ISSUE TITLE
Length limit for digilines?

### ISSUE THREAD

**Issue by jhdulaney** [Jeija/minetest-mod-digilines#29]
Hello, it appears that there is a length limit for digilines?  It seems that I get to a certain point, the signal stops propagating.

**Comment by Jeija** [comment]
There is no range limit for digilines imposed by digilines themselves, you are most likely running into the limitations of minetest. The same "range limit" would be present when using mesecons.

This is a well-known issue and I have proposed improvements upon the current way of handling things a long time ago (https://www.youtube.com/watch?v=B0YwfGVp3o8, and https://github.com/minetest/minetest/pull/1884), but since those changes may increase CPU usage by something like 10-20% on small servers like the Raspberry Pi, they have not been merged. I don't think there is anything digilines can do about it.

**Comment by jhdulaney** [comment]
Okay, added the patch; it appears to have not made a difference.
